from __future__ import annotations

DISK_KEYWORDS: tuple[str, ...] = (
    "disco",
    "ssd",
    "hd",
    "nvme",
    "armazenamento",
    "storage",
    "disk",
    "disk usage",
    "filesystem",
    "file system",
    "espaço",
    "espaco",
    "espaço livre",
    "espaco livre",
    "espaço em disco",
    "espaco em disco",
    "uso de disco",
    "df",
    "df -h",
    "partição",
    "particao",
    "partições",
    "particoes",
    "volume",
    "volumes",
    "montagem",
    "mount",
    "mount point",
    "ocupação do disco",
    "ocupacao do disco",
    "quanto espaço tenho",
    "quanto espaco tenho",
    "quanto espaço livre tenho",
    "quanto espaco livre tenho",
    "mostrar disco",
    "mostre o disco",
    "ver disco",
    "veja o disco",
)
