from __future__ import annotations

DOCKER_KEYWORDS: tuple[str, ...] = (
    "docker",
    "docker compose",
    "compose",
    "container",
    "containers",
    "imagem",
    "imagens",
    "image",
    "images",
    "docker ps",
    "docker images",
    "docker run",
    "docker exec",
    "docker logs",
    "docker pull",
    "docker build",
    "docker stop",
    "docker start",
    "docker restart",
    "docker rm",
    "docker rmi",
    "docker network",
    "docker volume",
    "docker system",
    "daemon docker",
    "instalar docker",
    "configurar docker",
    "engine",
    "containerização",
    "containerizacao",
    "docker engine",
    "registry",
    "docker hub",
    "compose up",
    "compose down",
    "compose logs",
    "compose build",
    "compose restart",
    "compose ps",
    "orquestração",
    "orquestracao",
)
