from __future__ import annotations

FILESYSTEM_KEYWORDS: tuple[str, ...] = (
    "arquivo",
    "arquivos",
    "diretório",
    "diretorio",
    "pasta",
    "pastas",
    "filesystem",
    "file system",
    "ls",
    "pwd",
    "cp",
    "mv",
    "rm",
    "mkdir",
    "rmdir",
    "touch",
    "find",
    "locate",
    "tree",
    "cat",
    "less",
    "more",
    "head",
    "tail",
    "chmod",
    "chown",
    "ln",
    "link",
    "symlink",
    "permissão",
    "permissao",
    "arquivo oculto",
    "hidden file",
    "listar arquivos",
    "conteúdo da pasta",
    "conteudo da pasta",
    "diretório atual",
    "diretorio atual",
    "working directory",
)
