from __future__ import annotations

GIT_KEYWORDS: tuple[str, ...] = (
    "git",
    "github",
    "gitlab",
    "clone",
    "commit",
    "push",
    "pull",
    "fetch",
    "merge",
    "rebase",
    "branch",
    "checkout",
    "switch",
    "tag",
    "stash",
    "status",
    "log",
    "diff",
    "restore",
    "reset",
    "remote",
    "origin",
    "fork",
    "repository",
    "repositório",
    "repositorio",
    "versionamento",
    "controle de versão",
    "controle de versao",
    "git add",
    "git commit",
    "git push",
    "git pull",
    "git status",
    "git branch",
    "git merge",
    "git rebase",
    "git fetch",
    "git clone",
)
