from __future__ import annotations

HARDWARE_KEYWORDS: tuple[str, ...] = (
    "hardware",
    "cpu",
    "processador",
    "lscpu",
    "núcleos",
    "nucleos",
    "threads",
    "socket",
    "arquitetura",
    "architecture",
    "x86",
    "x86_64",
    "amd64",
    "arm",
    "memória",
    "memoria",
    "ram",
    "gpu",
    "placa de vídeo",
    "placa de video",
    "video",
    "vga",
    "nvidia",
    "amd",
    "intel",
    "disco",
    "ssd",
    "hd",
    "nvme",
    "usb",
    "pci",
    "pcie",
    "motherboard",
    "placa mãe",
    "placa mae",
    "bios",
    "uefi",
    "equipamento",
    "máquina",
    "maquina",
)
