from __future__ import annotations

MEMORY_KEYWORDS: tuple[str, ...] = (
    "memória",
    "memoria",
    "ram",
    "memory",
    "free",
    "free -h",
    "swap",
    "memória ram",
    "memoria ram",
    "uso de memória",
    "uso de memoria",
    "consumo de memória",
    "consumo de memoria",
    "memória usada",
    "memoria usada",
    "memória livre",
    "memoria livre",
    "memória disponível",
    "memoria disponivel",
    "ram livre",
    "ram usada",
    "quanto de memória",
    "quanto de memoria",
    "quanta memória",
    "quanta memoria",
    "quanto de ram",
    "uso da ram",
    "estatísticas de memória",
    "estatisticas de memoria",
)
