from __future__ import annotations

NETWORK_KEYWORDS: tuple[str, ...] = (
    "rede",
    "network",
    "ip",
    "ip addr",
    "ip address",
    "ip route",
    "gateway",
    "dns",
    "hostname",
    "host",
    "ethernet",
    "wifi",
    "wi-fi",
    "wireless",
    "lan",
    "wan",
    "interface",
    "interfaces",
    "interfaces de rede",
    "adaptador",
    "adaptador de rede",
    "placa de rede",
    "endereço ip",
    "endereco ip",
    "meu ip",
    "ip local",
    "ip público",
    "ip publico",
    "conexão",
    "conexao",
    "internet",
    "ping",
    "latência",
    "latencia",
    "rota",
    "roteamento",
    "mostrar ip",
    "mostrar rede",
    "status da rede",
    "conectividade",
)
