from __future__ import annotations

PROCESSES_KEYWORDS: tuple[str, ...] = (
    "processo",
    "processos",
    "process",
    "ps",
    "ps aux",
    "top",
    "htop",
    "pid",
    "kill",
    "killall",
    "pkill",
    "renice",
    "nice",
    "cpu",
    "memória",
    "memoria",
    "uso de cpu",
    "consumo de cpu",
    "consumo de memória",
    "consumo de memoria",
    "listar processos",
    "mostrar processos",
    "processos ativos",
    "processos rodando",
    "running process",
    "foreground",
    "background",
    "thread",
    "threads",
    "task",
    "tarefas",
    "jobs",
    "job",
    "executando",
    "execução",
    "execucao",
    "monitorar processo",
    "encerrar processo",
    "finalizar processo",
    "matar processo",
)
