from __future__ import annotations

SERVICES_KEYWORDS: tuple[str, ...] = (
    "service",
    "services",
    "serviço",
    "servico",
    "systemctl",
    "daemon",
    "daemon reload",
    "iniciar serviço",
    "iniciar servico",
    "parar serviço",
    "parar servico",
    "reiniciar serviço",
    "reiniciar servico",
    "restart",
    "start",
    "stop",
    "status",
    "enable",
    "disable",
    "reload",
    "masked",
    "unmask",
    "systemd",
    "journalctl",
    "logs do serviço",
    "logs do servico",
    "serviços ativos",
    "servicos ativos",
    "serviços",
    "servicos",
    "background service",
    "boot service",
    "startup",
    "auto start",
    "serviço falhou",
    "servico falhou",
    "failed service",
    "running service",
    "active service",
    "inactive service",
)
