from __future__ import annotations

USERS_KEYWORDS: tuple[str, ...] = (
    "usuário",
    "usuario",
    "usuários",
    "usuarios",
    "whoami",
    "id",
    "groups",
    "passwd",
    "sudo",
    "root",
    "login",
    "logout",
    "sessão",
    "sessao",
    "grupo",
    "grupos",
    "useradd",
    "usermod",
    "userdel",
    "groupadd",
    "groupdel",
    "permissões",
    "permissoes",
    "autenticação",
    "autenticacao",
    "credenciais",
    "conta",
    "conta de usuário",
    "conta de usuario",
    "quem está logado",
    "quem esta logado",
    "usuário atual",
    "usuario atual",
    "administrador",
    "superusuário",
    "superusuario",
    "uid",
    "gid",
)
